# Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule {
  name = windowrule-1
  tag = +jetbrains-splash
  match:class = ^(jetbrains-.*)$
  match:title = ^(splash)$
  match:float = 1
}

windowrule {
  name = windowrule-2
  center = on
  no_focus = on
  border_size = 0
  match:tag = jetbrains-splash
}


# Center popups/find windows
windowrule {
  name = windowrule-3
  tag = +jetbrains
  min_size = (monitor_w*0.5) (monitor_h*0.5)
  match:class = ^(jetbrains-.*)
  match:title = ^()$
  match:float = 1
}

windowrule {
  name = windowrule-4
  center = on
  stay_focused = on
  border_size = 0
  match:tag = jetbrains
}


# Enabling this makes it possible to provide input in popup dialogs (search window, new file, etc.)

# For some reason tag:jetbrains does not work for size rule

# Disable window flicker when autocomplete or tooltips appear
windowrule {
  name = windowrule-5
  no_initial_focus = on
  match:class = ^(jetbrains-.*)$
  match:title = ^(win.*)$
  match:float = 1
}


# Disable mouse focus
windowrule {
  name = windowrule-6
  no_follow_mouse = on
  match:class = ^(jetbrains-.*)$
}


