# Webcam overlay for screen recording
windowrule {
  name = windowrule-1
  float = on
  pin = on
  no_initial_focus = on
  no_dim = on
  match:title = WebcamOverlay
}

windowrule {
  name = windowrule-2
  move = ((monitor_w*1)-window_w-40) ((monitor_h*1)-window_h-40)
  match:title = WebcamOverlay # There's a typo in the hyprland rule so 100%-w on the height param is actually correct here
}


